Update hashgraph-transfer.md
hiero-ledger/hiero pull request #26
Opened 2024-11-22 08:15 UTC by hendrikebbers

Added some information of Post-Transfer work

2024-11-22 16:26 UTC, rbarkerSL requested changes

2024-11-22 16:26 UTC, rbarkerSL commented on hashgraph-transfer.md
> +
```suggestion
```

I think all of this should go in a different document. The content described here does not really relate to the transfer steps that are defined in this document. 

I recommend adding a post-transfer readme file for the repository maintainers to utilize

2024-11-22 19:46 UTC, rwalworth approved these changes
Content looks good!

2026-08-11 17:17 UTC, jwagantall commented
Closed since this is stale. Feel free to re-open if is still needed,

2026-08-11 17:17 UTC, closed without merging